### ISSUE TITLE
Builds are failing

### ISSUE THREAD

**Issue by ondras12345** [jojo141185/mopidy-docker#29] opened 2024-06-09 19:09 UTC
Hi,
it seems like all the daily Github Actions builds in the last 2 month have failed: https://github.com/jojo141185/mopidy-docker/actions
The last one that passed seems to be manually triggered from the [`update-dependencies`](https://github.com/jojo141185/mopidy-docker/compare/main...update-dependencies) branch.
Is it be possible to merge `update-dependencies` into `main` or is there something blocking it?

**Comment by jojo141185** [comment] 2024-06-18 18:25
The problem is that the mopidy-spotify module in the current development already depends on the non-public release mopidy 4.0 alpha. 
I have now jumped back to the last available pre-release and temporarily deactivated the image version tagged by "latest". Not a great solution, but a quick work around until the next major release of mopidy will be available. 
Can you test one of the new images e.g. the one tagged with "test-release"? 
If it works, I would merge the fix into the main branch.

**Comment by ondras12345** [comment] 2024-06-18 19:15
I have installed `jojo141185/mopidy:test_release` on arm64, tested mopidy-spotify and it seems to be working.
Thanks for looking into this.

**Comment by jojo141185** [comment] 2024-06-19 00:18
Thanks, for your quick testing of the new image! 
I have merged all the changes, and the issue should be resolved now.

**Closed** 2024-06-19 10:32 UTC
