### ISSUE TITLE
can't launch the docker 

### ISSUE THREAD

**Issue by Yumega** [jojo141185/mopidy-docker#19] opened 2023-06-29 14:12 UTC
stderr: [dumb-init] /entrypoint.sh: Permission denied
stderr: [dumb-init] /entrypoint.sh: Permission denied
stderr: [dumb-init] /entrypoint.sh: Permission denied
stderr: [dumb-init] /entrypoint.sh: Permission denied
stderr: [dumb-init] /entrypoint.sh: Permission denied
stderr: [dumb-init] /entrypoint.sh: Permission denied
stderr: [dumb-init] /entrypoint.sh: Permission denied

**Comment by jojo141185** [comment] 2023-06-30 22:46
This seems to be a duplicate of https://github.com/jojo141185/mopidy-docker/issues/3

If you have problems with permission errors, try with user root first. If it works, make sure that the original user has sufficient permissions.

**Closed** 2023-08-06 14:39 UTC
